# Generated by Django 4.0 on 2021-12-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('idfilm', models.AutoField(db_column='idFilm', primary_key=True, serialize=False)),
                ('namefilm', models.CharField(db_column='nameFilm', max_length=45)),
                ('aboutfilm', models.CharField(db_column='aboutFilm', max_length=450)),
            ],
            options={
                'db_table': 'films',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('idgenres', models.AutoField(db_column='idGenres', primary_key=True, serialize=False)),
                ('namegenre', models.CharField(db_column='NameGenre', max_length=45)),
                ('aboutgenre', models.CharField(db_column='AboutGenre', max_length=450)),
            ],
            options={
                'db_table': 'genres',
                'managed': False,
            },
        ),
    ]
